export {
	APIFUSE__CDP_POOL__URL,
	APIFUSE__RESOLVER__2CAPTCHA__API_KEY,
	APIFUSE__RESOLVER__CAPMONSTER__API_KEY,
	APIFUSE__RESOLVER__CAPSOLVER__API_KEY,
	APIFUSE__RESOLVER__HYPERSOLUTIONS__API_KEY,
	APIFUSE__RESOLVER__TIMEOUT_MS,
	bindResolverSignal,
	createResolverClient,
	createResolverClientFromEnv,
	createUnsupportedResolverClient,
	DEFAULT_RESOLVER_VENDOR_PREFERENCE,
	DEFAULT_RESOLVER_TIMEOUT_MS,
	getResolverSolutionSource,
	invalidateCachedResolverSolution,
	invalidateResolverSolution,
	RESOLVER_ADAPTER_REGISTRY,
	RESOLVER_INSTRUMENTATION_METADATA,
	resolveProviderResolverVendors,
	type ResolverAdapterFactory,
	type ResolverInstrumentationMetadata,
	type ResolverRuntimeOptions,
	type ResolverSolutionSource,
} from "./resolver.js";
export {
	type ResolverCacheReadTelemetryEvent,
	type ResolverCacheWriteTelemetryEvent,
	type ResolverFailoverTelemetryEvent,
	type ResolverIdentityTelemetryEvent,
	type ResolverOutcomeTelemetryEvent,
	type ResolverTelemetryAttemptOutcome,
	type ResolverTelemetryCacheStatus,
	type ResolverTelemetryCacheWriteReason,
	type ResolverTelemetryErrorClass,
	type ResolverTelemetryIdentitySource,
	type ResolverTelemetryOutcome,
	type ResolverTelemetryPhase,
	type ResolverTelemetrySink,
	type ResolverVendorAttemptTelemetryEvent,
} from "./resolver-telemetry.js";
export type { ResolverVendorUnavailableReason } from "./resolver-vendors/types.js";
