import { expect, it } from "bun:test";
import { createHash } from "node:crypto";
import { cookieValuesFromHeaders, StealthCookieJar } from "../runtime/stealth-cookies.js";

it("shared Set-Cookie parsing preserves the 48 base stealth cookie snapshots byte-for-byte", () => {
	const cases = [
		["sid=abcdef123456; Path=/"],
		["sid=abcd; Domain=.example.com; Path=/; Secure"],
		["sid=abcd; Path=/account"],
		["a=abcd; Path=/", "b=efgh; Path=/"],
		["sid=abcd; Path=/; HttpOnly; SameSite=Strict"],
		["sid=abcd; Path=/; Expires=Thu, 01 Jan 1970 00:00:00 GMT"],
		["sid=abcd; Path=/", "sid=efgh; Path=/account"],
		["sid=abc; Path=/", "other=long-value; Path=/"],
	];
	const urls = [
		"https://example.com/",
		"http://example.com/",
		"https://example.com/account",
		"https://example.com/account/x",
		"https://sub.example.com/",
		"https://other.test/",
	];
	const snapshots = [];
	for (const headers of cases)
		for (const url of urls) {
			const registered: string[] = [];
			const jar = new StealthCookieJar(headers, "https://example.com/", (value) =>
				registered.push(value),
			);
			snapshots.push({
				headers,
				url,
				all: jar.getAll(url),
				header: jar.toHeader(url),
				names: jar.names(url),
				flat: jar.snapshot(),
				registered,
			});
		}
	expect(snapshots).toHaveLength(48);
	// Generated by executing the same fixture against 25f5262 (stealth is byte-identical to beafbf7).
	expect(createHash("sha256").update(JSON.stringify(snapshots)).digest("hex")).toBe(
		"87c3096a9e6d1183078dd6ddbcfc8797ff58cf3cf16a7a149f2b343eae315bbb",
	);
});

it("Set-Cookie parsing extracts values independently of cookie attributes", () => {
	expect(
		cookieValuesFromHeaders([
			"sid=abcdef123456; Path=/; HttpOnly",
			"other=second-value; Expires=Thu, 01 Jan 2037 00:00:00 GMT",
		]),
	).toEqual(["abcdef123456", "second-value"]);
});
