// This set suppresses the unregistered-provider-error-code signal for codes
// intentionally emitted by SDK paths. It is not the complete authority for
// runtime error resolution: branded errors and additional canonical SDK codes
// must also remain immune to provider-declared status/retryability overrides.
export const SDK_OWNED_PROVIDER_ERROR_CODES = new Set([
	"MISSING_SECRET",
	"AUTH_PROMPT_UNAVAILABLE",
	"BROWSER_CDP_POOL_REQUIRED",
	"BROWSER_RUNTIME_UNSUPPORTED",
	"STEALTH_RUNTIME_UNSUPPORTED",
	"SSE_EVENT_UNDECLARED",
	"STREAM_EVENT_TOO_LARGE",
	"STREAM_CHUNK_TOO_LARGE",
	"SSE_RESULT_UNSUPPORTED",
	"STREAM_RESULT_UNSUPPORTED",
	"AUTH_FLOW_NOT_CONFIGURED",
	"refresh_not_supported",
	"RUNTIME_UNSUPPORTED",
	"PROVIDER_STATE_UNSUPPORTED",
	"CHOICE_TOKEN_MASTER_SECRET_NOT_CONFIGURED",
	"CHOICE_STATE_PAYLOAD_TOO_LARGE",
	"CHOICE_STATE_UNAVAILABLE",
	"CHOICE_CONTEXT_REQUIRED",
	"unsupported_stealth_cookie_store_version",
	"provider_secret_error",
	"credential_key_error",
	"credential_mode_error",
	"flow_expired",
	"turn_validation_error",
	"context_access_error",
	"UNSUPPORTED_STT_OPTION",
	"INVALID_STT_AUDIO",
	"STT_AUDIO_TOO_LARGE",
	"STT_UPSTREAM_FAILED",
	"INVALID_STT_VERIFICATION_CODE_OPTIONS",
	"NO_CODE_FOUND",
	"AMBIGUOUS_CODE",
	"retry_invalid_policy",
	"retry_unsafe_method",
	"stealth_cookie_store_serialize_failed",
	"response_too_large",
	"transport_stream_unavailable",
	"transport_invalid_method",
	"http_transport_override_unsupported",
	"http_redirect_policy_invalid",
	"http_redirect_stopped",
	"http_redirect_max_hops",
	"http_redirect_missing_location",
	"http_redirect_loop",
	"transport_invalid_url",
	"retry_exhausted",
	"auth_abort_unsafe_data",
	"credentials_auth_missing_credential_keys",
	"credentials_auth_missing_credential",
	"credentials_auth_invalid_login_result",
	"credentials_auth_unknown_challenge",
	"credentials_auth_unknown_pending_challenge",
	"STATEFUL_FORWARDING_NOT_CONFIGURED",
	"STATEFUL_FORWARDING_SIGNATURE_MISSING",
	"STATEFUL_FORWARDING_NONCE_INVALID",
	"STATEFUL_FORWARDING_TIMESTAMP_INVALID",
	"STATEFUL_FORWARDING_SIGNATURE_INVALID",
	"STATEFUL_FORWARDING_REPLAY_DETECTED",
	"STATEFUL_FORWARDING_REPLAY_CACHE_FULL",
	"STATEFUL_FORWARDING_ENVELOPE_INVALID",
	"STATEFUL_FORWARDING_PROVIDER_MISMATCH",
	"STATEFUL_FORWARDING_SOURCE_POD_MISMATCH",
	"STATEFUL_FORWARDING_OWNER_FENCE_INVALID",
	"STATEFUL_FORWARDING_REQUEST_FAILED",
	"STATEFUL_FORWARDING_CONTEXT_MISSING",
	"STATEFUL_FORWARDING_BAD_RESPONSE",
	"STATEFUL_INTERNAL_EXECUTOR_NOT_CONFIGURED",
	"STATEFUL_FILE_FORWARDING_UNSUPPORTED",
	"STATEFUL_CONTROL_PLANE_OPERATION_AMBIGUOUS",
	"STATEFUL_CONTROL_PLANE_REQUEST_FAILED",
	"STATEFUL_CONTROL_PLANE_HTTP_ERROR",
	"STATEFUL_CONTROL_PLANE_INVALID_RESPONSE",
]);

// Complete code authority for provider-declared runtime resolution. Keep this
// separate from signal suppression: declarations may document these codes, but
// their status and retryability can never override the SDK's canonical result.
export const SDK_RUNTIME_OWNED_ERROR_CODES = new Set([
	...SDK_OWNED_PROVIDER_ERROR_CODES,
	"reauth_required",
	"STT_UNAVAILABLE",
	"UNSUPPORTED_STT_BACKEND",
	"OUTPUT_VALIDATION_FAILED",
	"NOT_FOUND",
	"not_found",
]);
