// @apifuse/provider-sdk

export * from "./auth.js";
export * from "./ceremonies/index.js";
export * from "./choice-token.js";
export type {
	ApiFuseConfig,
	BrowserConfig,
	ProxyCacheStatus,
	ProxyProtocol,
	ProxyResolutionOptions,
	ProxyResolutionSource,
	ProxyUserAgentSource,
	ProxyVendorName,
	ResolvedProxyConfig,
	SessionConfig,
	SmartproxyAllocatorBodyClass,
} from "./config/loader.js";
export { defineConfig, loadApiFuseConfig, resolveProxy } from "./config/loader.js";
export {
	canonicalJson,
	digestProviderContract,
	extractProviderContract,
	type JsonPrimitive,
	type JsonValue,
	PROVIDER_CONTRACT_SCHEMA_VERSION,
	type ProviderContractOperation,
	type ProviderContractSnapshot,
} from "./contract.js";
export {
	centered,
	delayed,
	defineHealthJourney,
	defineOperation,
	defineProvider,
	defineSmsOtpMatcher,
	defineStreamOperation,
	every,
	type AuthStartNoInputGuard,
	type OperationDefinitionFor,
	type ProviderBuilder,
	type ProviderContextOf,
	type ProviderDeclaration,
	type ProviderDefinitionFor,
} from "./define.js";
export {
	AssertionExpressionSchema,
	AssertionPredicateSchema,
	AssertStepSchema,
	BoundedJsonPathSchema,
	CandidateBlockSchema,
	CandidatePolicySchema,
	CredentialRefDeclarationSchema,
	defineHealthScenario,
	HealthScenarioSchema,
	HealthStepSchema,
	ExtractStepSchema,
	FindFirstSchema,
	GuardStepSchema,
	JournalPolicySchema,
	JsonTemplateSchema,
	ManualTriggerPolicySchema,
	OperandSchema,
	OperationStepSchema,
	QuantifierSchema,
	ReferenceSchema,
	RetryPolicySchema,
	SafeRegexSchema,
	ScopedAssertionExpressionSchema,
	ScopedAssertionPredicateSchema,
	ScopedItemReferenceSchema,
	ScopedOperandSchema,
	StepReferenceSchema,
	RelativeDateNodeSchema,
	ValueTypeSchema,
} from "./health-scenario.js";
export type {
	AssertionExpression,
	AssertionPredicate,
	AttemptReference,
	AssertResult,
	AssertStep,
	BoundedJsonPath,
	CandidateBlock,
	CandidatePolicy,
	CandidateReference,
	CredentialReference,
	CredentialRefDeclaration,
	EstablishedConnectionReference,
	ExtractStep,
	FindFirst,
	GuardAttribution,
	GuardReasonCode,
	GuardResult,
	GuardStep,
	HealthScenario,
	HealthStep,
	JsonTemplate,
	JournalPolicy,
	ManualTriggerPolicy,
	NonEmpty,
	OperationResult,
	OperationStep,
	Operand,
	Quantifier,
	ReferenceNode,
	Reference,
	RelativeDateNode,
	RetryPolicy,
	SafeRegex,
	ScopedAssertionExpression,
	ScopedAssertionPredicate,
	ScopedItemReference,
	ScopedOperand,
	StepBase,
	StepReference,
	ExtractResult,
	ValueType,
} from "./health-scenario.js";
export type { DevServerOptions } from "./dev.js";
export { createDevServer, startDevServer } from "./dev.js";
export * from "./errors.js";
export * from "./engine.js";
export * from "./observability.js";
export * from "./user-input.js";
export * from "./i18n/index.js";
export {
	type LintDiagnostic,
	lintOperation,
	lintProvider,
} from "./lint.js";
export * from "./recipes/gov-api.js";
export * from "./recipes/rest-api.js";
export { createFlowContext, createScratchpad } from "./runtime/auth-flow.js";
export type { BrowserClientOptions } from "./runtime/browser.js";
export {
	APIFUSE__CACHE__KEY_PEPPER_ENV,
	createBypassProviderCache,
	createProviderCache,
	type ProviderCacheOptions,
} from "./runtime/cache.js";
export {
	type CreateProviderChoiceContextOptions,
	createProviderChoiceContext,
	createTestProviderChoiceContext,
	PROVIDER_RUNTIME_CHOICE_TOKEN_MASTER_SECRET_ENV,
} from "./runtime/choice.js";
export {
	type CreateCredentialContextOptions,
	createCredentialContext,
} from "./runtime/credential.js";
export { createEnvContext } from "./runtime/env.js";
export { executeOperation } from "./runtime/executor.js";
export { createHttpClient } from "./runtime/http.js";
export {
	NativeEgressGrantExpiredError,
	NativeEgressNotDeclaredError,
	NativeIdleTimeoutError,
	NativeNetworkError,
	NativeProxyExpiredError,
} from "./runtime/native-network-errors.js";
export type {
	NativeGatewayProxy,
	NativeGatewayProxyResolutionInput,
	NativeGatewayProxySkipReason,
	NativeGatewayProxySynthesizer,
	NativeGatewayProxySynthesisResult,
	NativeGatewayProxySynthesisInput,
	NativeNetworkClientOptions,
	NativeNetworkErrorCode,
	VendorCredentialLookup,
	VendorCredentialResolver,
} from "./runtime/native-network.js";
export type { Insight, InsightSeverity } from "./runtime/insights.js";
export { generateInsights } from "./runtime/insights.js";
export {
	type InstrumentationOptions,
	type InstrumentedProviderContext,
	wrapWithInstrumentation,
} from "./runtime/instrumentation.js";
export type { PrevalidateResult } from "./runtime/prevalidate.js";
export { getProviderBaseUrl } from "./runtime/provider.js";
export type {
	ProxyTelemetryLogPayload,
	ProxyTelemetryResolvedPayload,
	ProxyTelemetryUnresolvedPayload,
} from "./runtime/proxy-telemetry.js";
export {
	APIFUSE__CDP_POOL__URL,
	APIFUSE__RESOLVER__2CAPTCHA__API_KEY,
	APIFUSE__RESOLVER__CAPMONSTER__API_KEY,
	APIFUSE__RESOLVER__CAPSOLVER__API_KEY,
	APIFUSE__RESOLVER__HYPERSOLUTIONS__API_KEY,
	APIFUSE__RESOLVER__TIMEOUT_MS,
	DEFAULT_RESOLVER_TIMEOUT_MS,
} from "./runtime/resolver-config.js";
export { createUnsupportedResolverClient } from "./runtime/resolver-shared.js";
export type { ResolverRuntimeOptions } from "./runtime/resolver.js";
export type { ResolverVendorTransport } from "./runtime/resolver-vendors/types.js";
export {
	assertRequiredSecretsPresent,
	listMissingRequiredSecrets,
	MISSING_SECRET_CODE,
} from "./runtime/secrets.js";
export {
	createUnsupportedProviderRuntimeState,
	UnsupportedProviderStateError,
} from "./runtime/state.js";
export {
	APIFUSE__OCR__API_KEY_ENV,
	APIFUSE__OCR__BACKEND_ENV,
	APIFUSE__OCR__BASE_URL_ENV,
	APIFUSE__OCR__CLOUDFLARE_API_TOKEN_ENV,
	APIFUSE__OCR__MODEL_ENV,
	CLOUDFLARE_ACCOUNT_ID_ENV,
	CLOUDFLARE_WORKERS_AI_OCR_BACKEND,
	createCloudflareWorkersAiOcrClient,
	createOcrClientFromEnv,
	createOpenAiCompatibleOcrClient,
	createUnsupportedOcrClient,
	DEFAULT_CLOUDFLARE_WORKERS_AI_OCR_MODEL,
	extractCaptchaCandidates,
	OPENAI_COMPATIBLE_OCR_BACKEND,
} from "./runtime/ocr.js";
export {
	APIFUSE__STT__BACKEND_ENV,
	APIFUSE__STT__CLOUDFLARE_API_TOKEN_ENV,
	APIFUSE__STT__MODEL_ENV,
	createSttClientFromEnv,
	createUnsupportedSttClient,
	extractVerificationCode,
	resolveSttPrompt,
} from "./runtime/stt.js";
export {
	type CreateTraceContextOptions,
	createTraceContext,
	type Span,
	type TraceContext,
} from "./runtime/trace.js";
export {
	APIFUSE_DESCRIPTION_KEY_META_KEY,
	APIFUSE_REDACTION_MARKER,
	APIFUSE_SENSITIVE_KIND_META_KEY,
	APIFUSE_SENSITIVE_META_KEY,
	collectSensitivePaths,
	describeKey,
	field,
	fields,
	isSensitiveSchema,
	redactPayload,
	type SensitiveFieldKind,
	type SensitiveFieldOptions,
	type SensitivePath,
	sensitive,
	z,
} from "./schema.js";
export {
	createServerApp,
	createServerAppAsync,
	ERROR_OBSERVABILITY_HEADER,
	type ProviderErrorCauseFrame,
	type ServeOptions,
	serve,
} from "./server/serve.js";
export {
	DEFAULT_STEALTH_BROWSER,
	DEFAULT_STEALTH_OS,
	getStealthProfile,
	listStealthProfiles,
} from "./stealth/profiles.js";
export * from "./stream.js";
export type {
	ApiFuseResponse,
	AutoSolveResolverFactory,
	AutoSolveResolverSelection,
	AuthConfig,
	AuthContext,
	AuthFlowDefinition,
	AuthFlowInputHandler,
	AuthFlowStartHandler,
	AuthMode,
	AuthTurn,
	Bcp47Locale,
	BrowserCookie,
	BrowserEngine,
	BrowserOptions,
	BrowserResourceBody,
	BrowserResourceDecision,
	BrowserResourceMethod,
	BrowserResourcePolicy,
	BrowserResourceRequest,
	BrowserResourceRoute,
	ChallengeSolution,
	ConnectionMode,
	ContextDeclaration,
	CookieJar,
	ContextScratchpad,
	CredentialContext,
	CredentialDeclaration,
	E164PhoneNumber,
	EnvContext,
	FlowContext,
	FlowContextStore,
	HealthCheckAssertionContext,
	HealthCheckCase,
	HealthCheckCaseResult,
	HealthCheckSuite,
	HealthCheckUnsupported,
	HealthJourneyDefinition,
	HealthJourneyEventContext,
	HealthJourneyGatewayContext,
	HealthJourneyJournalContext,
	HealthJourneyManualTriggerPolicy,
	HealthJourneyRunContext,
	HealthJourneyRunResult,
	HealthJourneySchedule,
	HealthScheduleRandomization,
	HealthJourneySmsContext,
	HealthJourneyStep,
	HttpClient,
	HttpMethod,
	HttpRedirectFailureReason,
	HttpRedirectPolicy,
	HttpRedirectPolicyMode,
	HttpResponse,
	HttpRetryOptions,
	HttpRetrySummary,
	HttpStreamResponse,
	IanaTimeZone,
	InferSchemaOutput,
	Iso3166Alpha2CountryCode,
	Iso4217CurrencyCode,
	Iso8601Duration,
	NativeContext,
	NativeNetworkClient,
	NativeNetworkCloseReason,
	NativeNetworkConnection,
	NativeNetworkConnectInput,
	NativeNetworkConnectOptions,
	NativeNetworkDynamicGrantOptions,
	NativeNetworkEgressGrant,
	NativeProviderConfig,
	NativeProxyDrainHandler,
	NativeProxyEgressInfo,
	NativeProxyExpiringEvent,
	NativeProxyExpiringReason,
	NativeTcpDynamicEgressRule,
	NativeTcpEgressGrant,
	NativeTcpEgressRule,
	NativeTcpPortRange,
	NativeTcpTlsMode,
	NativeTlsConnectOptions,
	OcrCaptchaCandidate,
	OcrCaptchaOptions,
	OcrCaptchaResult,
	OcrContext,
	OcrImageInput,
	OcrRecognizeRequest,
	OcrResult,
	OcrWarning,
	OperationApprovalPolicy,
	OperationContractMetadata,
	OperationDefinition,
	OperationDeprecationMetadata,
	OperationExample,
	OperationErrorCode,
	ProviderErrorStatus,
	OperationHandlerResult,
	OperationLifecycle,
	OperationObservabilityConfig,
	OperationObservabilitySensitiveConfig,
	OperationRelationships,
	OperationRiskClass,
	OperationSensitivePath,
	OperationTransport,
	OperationTransportKind,
	ProbeInterval,
	ProviderAccessConfig,
	ProviderAccessVisibility,
	ProviderCache,
	ProviderCacheGetOrSetOptions,
	ProviderCacheKeyOptions,
	ProviderCacheLookupMeta,
	ProviderCacheResponseMeta,
	ProviderCacheResult,
	ProviderChoiceBindingOptions,
	ProviderChoiceConsumeMode,
	ProviderChoiceConsumeResult,
	ProviderChoiceContext,
	ProviderChoiceExplicitParseResult,
	ProviderChoiceIssueOptions,
	ProviderChoiceParseOptions,
	ProviderChallenge,
	ProviderChallengeKind,
	ProviderContext,
	ProviderContextFor,
	ProviderDefinition,
	ProviderDeploymentOverrides,
	ProviderFileRef,
	ProviderFilesContext,
	ProviderHealthMonitorConfig,
	ProviderHealthProbeConfig,
	ProviderLocale,
	ProviderLocaleKey,
	ProviderLocaleKeyInput,
	ProviderLogoProfile,
	ProviderLogoSource,
	ProviderMeta,
	ProviderOcrConfig,
	ProviderProxyConfig,
	ProviderProxyMode,
	ProviderProxyPolicy,
	ProxiedOAuthConfig,
	ProviderProxyProvider,
	ProviderProxySessionAffinity,
	ProviderPublicConnectionMode,
	ProviderPublicProfile,
	ProviderReviewed,
	ProviderResolvedFile,
	ProviderResolverConfig,
	ProviderResolverVendor,
	ProviderRuntimeTarget,
	ProviderRuntimeState,
	ProviderSecretDeclaration,
	ProviderStealthConfig,
	ProviderStateDurationString,
	ProviderStateNamespace,
	ProviderStreamEvent,
	ProviderSttConfig,
	ProviderSttMode,
	ProviderSupportLevel,
	RequestOptions,
	RedirectRunReason,
	ResolverContext,
	Rfc3339Instant,
	SchemaLike,
	SmsOrigin,
	SmsOtpExtractionPattern,
	SmsOtpMatcherDefinition,
	SseMessage,
	StandardSchemaV1,
	StateCasResult,
	StateNamespaceOptions,
	StateNamespaceScope,
	StateValue,
	StateWriteOptions,
	StealthClient,
	StealthBrowser,
	StealthChallengeClassification,
	StealthCookieStore,
	StealthCookieStoreV1,
	StealthFetchOptions,
	StealthPlatform,
	StealthProfile,
	StealthProfileDescriptor,
	StealthProfileSelection,
	StealthOS,
	StealthRedirectHop,
	StealthRedirectRunOptions,
	StealthRedirectRunResult,
	StealthResponse,
	StealthSession,
	StealthSessionCookies,
	SttAudioInput,
	SttContext,
	SttPromptPolicy,
	SttSegment,
	SttTranscribeMode,
	SttTranscribeRequest,
	SttTranscript,
	SttUnsupportedOptionPolicy,
	SttUsage,
	SttVerificationCodeOptions,
	SttWarning,
	TraceConfig,
	TraceSpan,
	VerificationCodeCandidate,
	VerificationCodeCandidateSource,
	VerificationCodeExtractionResult,
} from "./types.js";
export {
	DEFAULT_OPERATION_TRANSPORT,
	HttpRetryAfterPolicy,
	HttpRetryDelayStrategy,
	HttpRetryJitter,
	HttpRetryPreset,
	HttpRetryUnsafeMethodPolicy,
	PROBE_INTERVALS,
	STREAM_CHUNK_BYTES_MAX,
	STREAM_CHUNK_BYTES_MIN,
	STREAM_HEARTBEAT_MS_MAX,
	STREAM_HEARTBEAT_MS_MIN,
	STREAM_IDLE_TIMEOUT_MS_MAX,
	STREAM_IDLE_TIMEOUT_MS_MIN,
	STREAM_MAX_DURATION_MS_MAX,
	STREAM_MAX_DURATION_MS_MIN,
} from "./types.js";
export * from "./utils/date.js";
export * from "./utils/parse.js";
export * from "./utils/text.js";
export * from "./utils/transform.js";
